### ISSUE TITLE
코드에 수정할 부분이 보입니다, cst_id, custKey 값이 클라이언트에 노출 되어도 상관 없는 값인가요?

### ISSUE THREAD

**Issue by Hot-key** [PAYPLECORP/sample_react#1]
일단 React 와 jquery를 같이 사용하는 부분에서 놀랐습니다.
여기까지는 그럴수 있지 하고 넘어갔는데
useState 사용법을 모르는것 같네요.

기본적으로 useState 에서 받은 값은 불번입니다.

지금 이런식으로 사용 중인데
```js
// Order.js
const [content] = useState({...});

const handleChange = (e) => {
    content[e.target.name] = e.target.value;
}
```

이런식으로 불변성을 위반하지 않도록 작성해야합니다.
```js
// Order.js
const [content, setContent] = useState({...});

const handleChange = (e: any) => {
    let tempContent = content;
    tempContent[e.target.name] = e.target.value;
    setContent(tempContent);
};
```

아니면 useRef 를 사용해야 하는 부분입니다.
```js
// Order.js
const content = useRef({});
  
const handleChange = (e: any) => {
  content.current[e.target.name] = e.target.value;
};
```

useState 는 상태 관리 용도입니다. 주로 rendering에 관련한 값에 사용하므로 불변성을 유지해야 하고
해당 값의 변경을 setState로 전달하여 변경된 사실을 알리는 작업이 필요합니다.

useRef는 rendering에 필요 없는 값을 지정하는데 사용합니다.
위의 값은 변경에 따라서 추가 render가 필요 없으므로 useRef를 사용하는편이 권장되고
useState를 사용해도 저런식으로 사용하면 안됩니다.

하단에 jquery 이용해서 작성하신 부분도 react 통해서 전부 가능한 부분인데
여기에 관해서는 말 안하겠습니다.

다음으로 authenticate.js 에 들어간 key 값 부분입니다.

```js
// authenticate.js
const form = new FormData();

form.append('cst_id', process.env.REACT_APP_CST_ID); 
form.append('custKey', process.env.REACT_APP_CUST_KEY);
```

아무리 샘플 소스라고 해도 이러면 클라이언트에 해당 키 값이 전부 노출됩니다.

React 로 작성한 코드는 기본적으로 client side 에서 돌아갑니다.
PHP, JSP 처럼 서버에서 처리되는 코드들이 아니라서 전부 클라이언트에서 접근이 가능한데
저런식으로 사용해도 되는 부분인가요?

해당키는 사용자에게 노출되어도 상관없는 키가 아닌이상 서버에서 받아서 처리하는걸로 해야 합니다

기본적으로 샘플코드는 돌아가기만 하는 코드가 아니라 보고 따라 할 수 있는 코드여야 한다고 생각하는데
혹시나 해당 샘플보고 따라서 작성할 사람이 있을까 해서 이슈 등록합니다.

다른건 몰라도 authenticate.js 부분은 따라 작성하면 안됩니다.

**Comment by csb-payple** [comment]
안녕하세요.
보내주신 내용에 따라, Key 정보를 서버단으로 이동 조치했습니다. 
감사합니다.
